### ISSUE TITLE
Default user credentials don't work

### ISSUE THREAD

**Issue by chagwood** [Fundator/IMO-Maritime-Single-Window#89]
**Describe the bug**

I have installed the app and have it running. When I try to authenticate with the username/password that is provided in the user guide, I get "invalid credentials"

**To Reproduce**
- Install application
- Populate DB using https://github.com/Fundator/IMO-Maritime-Single-Window/blob/master/IMOMaritimeSingleWindow/Server/SqlScripts/Create_and_populate_DB.sql
- Run application
- Attempt to login using **admin@imo-msw.org** / **admin** fails

**Expected behavior**
- Being able to login

**Comment by bardlokas** [comment]
This is due to the script that has been uploaded. It contains the wrong username/password combo according to the document. I will fix this,  thanks for bringing it to my attention.

**Comment by bardlokas** [comment]
Solved by #90 

You can now run the database script again and login using default credentials listed in the user doc.
