### ISSUE TITLE
problem=

### ISSUE THREAD

**Issue by mgalil** [Fundator/IMO-Maritime-Single-Window#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
after I finished the all setup steps at this link https://github.com/Fundator/IMO-Maritime-Single-Window, I try to open the application, I get the following error:
![image](https://user-images.githubusercontent.com/52276460/61204215-e8383080-a6ec-11e9-8881-2bca032ca38b.png)
can you help me to solve this problem?

**Comment by mgalil** [comment]
inserted before

**Comment by bardlokas** [comment]
I am currently out on travel, so sorry for late response
did you manage to fix the issue?
