### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mgalil** [Fundator/IMO-Maritime-Single-Window#95]
**Describe the bug**
after I have finished all setup steps at this link https://github.com/Fundator/IMO-Maritime-Single-Window
I try to open the url "http://localhost:4201/" but I get the following error:
![imo](https://user-images.githubusercontent.com/52276460/61274365-f731e800-a7ab-11e9-96fc-ada4b5172ce0.PNG)

can you help me to solve this problem?

**Comment by bardlokas** [comment]
I am currently travelling.Will look into this when I am available.

**Comment by mgalil** [comment]
Have a nice trip and come back soon.

I'm waiting for your great reply

**Comment by bardlokas** [comment]
Are you sure you are on the latest release of the software?
"app-dpg-confirmation-view" was removed 15 days ago. Try cloning the repo again and let me know if the error persists.

**Comment by mgalil** [comment]
the you very much for your reply,
I will try the latest release, then I will feedback you.

**Comment by mgalil** [comment]
Hi bardlokas,

Hope you have a good day.

After I installed the latest version, I get login screen and entered credentials agent@imo-msw.org/agent, faced the following error "500 Internal server error"

![image](https://user-images.githubusercontent.com/52276460/62276021-6dd51380-b443-11e9-924d-7ec3887a2aaf.png)
