### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by mgalil** [Fundator/IMO-Maritime-Single-Window#96]
After I have installed the latest version, I get login screen and entered credentials agent@imo-msw.org/agent, faced the following error "500 Internal server error"
and imo logo did not displayed.

![62276021-6dd51380-b443-11e9-924d-7ec3887a2aaf 1](https://user-images.githubusercontent.com/52276460/62422769-070c6000-b6b8-11e9-9aad-0f7dd772c712.png)

**Comment by bardlokas** [comment]
Is your database up and running?

Can you access it from pgadmin? 

Are the names of the db correct in regards to the Appsettings.json file?

Does the localhost:5000 Page work?

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/62423784-818fac80-b6c5-11e9-94b4-8b47fffe21df.png)
![image](https://user-images.githubusercontent.com/52276460/62423804-fc58c780-b6c5-11e9-9556-6325e8cb8a7d.png)

Appsettings.json:
{
	"ConnectionStrings": {
		"OpenSSN": "User ID=user;Password=Root1234;Host=localhost;Port=5432;Database=imomsw;",
		"UserDatabase": ""
	},
	"AppSettings": {
		"Secret" : "TopSekritSecretToken"
	}
}

**Comment by bardlokas** [comment]
And you get the same error on 5000 when logging in?
Can you send me the complete error?

**Comment by bardlokas** [comment]
When you launch the project.Can you see it as a user liste as connected from pgadmin?

**Comment by mgalil** [comment]
yes get the same error on 5000.
"When you launch the project.Can you see it as a user liste as connected from pgadmin?" 
I didn't understand? please more clarification

**Comment by bardlokas** [comment]
When you run the project as instructed in the readme. Can you see the user you reference in the aposettings file as a connected user when looking in pgadmin? It will be listed as a session next to the postgres user

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/62453629-02f14880-b773-11e9-864d-2a6b84e56ded.png)

**Comment by bardlokas** [comment]
What version of the SQL script did you run?

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/62460284-e7da0500-b781-11e9-9cf2-87016acfd541.png)

**Comment by mgalil** [comment]
I have run the most recent script you provide me at the above link, but again get the same error ""500 Internal server error"

**Comment by bardlokas** [comment]
And on localhost 5000?

**Comment by mgalil** [comment]
Hi bardlokas,
any update !

**Comment by mgalil** [comment]
yes, get the same error on localhost 5000.

**Comment by mgalil** [comment]
any update ...

**Comment by bardlokas** [comment]
Sorry for the late response, this issue occured in the middle of my travels. 
Can you send me an email with the error displayed in the console of your browser?
email: **post@bardlokas.no**

**Comment by bardlokas** [comment]
Has the issue been resolved?

**Comment by mgalil** [comment]
any news !

**Comment by bardlokas** [comment]
Did you see my last reply? I need some more information to be able to help you. Can you open the console of your browser and show me what it says when that error appears?
To open the console press F12 and select "console".

**Comment by mgalil** [comment]
Hi bardlokas ,

I'm so sorry, I was on vacation for Eid al-Adha feast and I didn't read your updates.
for http://localhost:4201:
![image](https://user-images.githubusercontent.com/52276460/63344899-cec07f00-c351-11e9-9b36-47846a89e585.png)

for http://localhost:5000:
![image](https://user-images.githubusercontent.com/52276460/63345001-02030e00-c352-11e9-96ea-ece7ddd418e5.png)

**Comment by bardlokas** [comment]
It doesnt show anything more than just "500 internal server error" ? What credentials are you trying to log in with?

**Comment by mgalil** [comment]
username: **agent@imo-msw.org**
password: **agent**

**Comment by bardlokas** [comment]
And you get no more information than "500 internal server error"?
You are on the latest branches of master ?

**Comment by mgalil** [comment]
yes, latest version...

**Comment by bardlokas** [comment]
The only error you get is "500 internal server error" It doesnt say anything more below that or a dropdown arrow you can click?

**Comment by bardlokas** [comment]
Are you able to start the server solution with visual studio in debug mode and see what the error is then?

**Comment by mgalil** [comment]
Ok .. I will try and feed you back.

**Comment by bardlokas** [comment]
By the way, what versions of npm and node are you on?
To check what version you have installed:
Open a command window (cmd) and type "node -v" and "npm -v".

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63503247-6ac3c500-c4cf-11e9-92e3-27d129b15b91.png)

**Comment by bardlokas** [comment]
That seems okay
I have something else you can try instead of running the server with visual studio if you are having issues with that:
In the cmd window where you ran the "dotnet watch run" command, the error should display.
So run the project as usual, try to login so you get the 500 error and look in the cmd window and look for the error there.

**Comment by bardlokas** [comment]
**If this is going to slow for you;**
You can send me an email at **post@bardlokas.no** and we can fix it faster via skype or something. I can then post the solution here for other people who might have the same issue.

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63507580-5637fa80-c4d8-11e9-9033-7d8764908c42.png)


![image](https://user-images.githubusercontent.com/52276460/63507641-7798e680-c4d8-11e9-8f4e-9b53773dbe9d.png)

**Comment by bardlokas** [comment]
Do you have a user set up in the DB with the name "user" ?

**Comment by bardlokas** [comment]
You can see your users in pgadmin.
1. Select your server
2. Select your database (imomsw)
3. Open the dropdown (login/group roles)
![bilde](https://user-images.githubusercontent.com/16537436/63508364-1c67f380-c4da-11e9-80f3-904f579f1279.png)

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63508886-263e2680-c4db-11e9-96a9-5af661044358.png)

**Comment by bardlokas** [comment]
Change your appsettings to point to "postgres" instead of "user".
If it still doesn't work change your settings to:
"        "OpenSSN": "User ID=postgres;Host=localhost;Port=5432;Database=imomsw;keepalive=60;",
"

**Comment by mgalil** [comment]
appsettings.json file content:

{
	"ConnectionStrings": {
		"OpenSSN": "User ID=postgres;Password=******;Host=localhost;Port=5432;Database=imomsw;",
		"UserDatabase": ""
	},
	"AppSettings": {
		"Secret" : "TopSekritSecretToken"
	}
}

**Comment by mgalil** [comment]
user was already "postgres" not "user"

**Comment by bardlokas** [comment]
Remove the password settings, so it looks the same as the one i posted above

**Comment by bardlokas** [comment]
And just to make sure:
you have a table named public."user" correct?

Also:
http://localhost:5000/api/Portcall/1

Does this page display any information (it should be showed in a .json format)

**Comment by mgalil** [comment]
- "imomsw" schema doesn't have any table although I have run sql script "Create_and_populate_DB.sql" successfully
- http://localhost:5000/api/Portcall/1 don't display any output

**Comment by bardlokas** [comment]
Did you get any error messages when running the sql script?

**Comment by bardlokas** [comment]
If you already have the "imomsw" database:
remove the line: "CREATE DATABASE imomsw WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C.UTF-8' LC_CTYPE = 'C.UTF-8';"
from the script before running it.

**Comment by bardlokas** [comment]
Has the issue been resolved?

**Comment by mgalil** [comment]
- "imomsw" schema doesn't have any table although I have run sql script "Create_and_populate_DB.sql" successfully
- http://localhost:5000/api/Portcall/1 don't display any output

**Comment by bardlokas** [comment]
Did you see my previous comment?
If the script ran successfully you should have tables. If you dont have any tables it didn't run succesfully.

**Comment by bardlokas** [comment]
An error should occur when trying to run the script. It mainly contains create table / insert into statements so if you have nothing most of it must've failed

**Comment by bardlokas** [comment]
You ran the script towards the wrong database. You have two options:
1. Change your appsettings to point to the "postgres" database instead of "imomsw"
2. Run the script on the "imomsw" database.

**Comment by mgalil** [comment]
I tried the two options .. but get the same error "500 Internal Server Error"

**Comment by bardlokas** [comment]
Can you verify that you have a table named "users" in your imomsw database?

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63835345-8fa8b400-c977-11e9-93a8-4702796519b7.png)


![image](https://user-images.githubusercontent.com/52276460/63835547-f4fca500-c977-11e9-8359-4d5a04b0fc2b.png)

![image](https://user-images.githubusercontent.com/52276460/63835590-0b0a6580-c978-11e9-86ac-111c52e1d28c.png)

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63835345-8fa8b400-c977-11e9-93a8-4702796519b7.png)

users table:

![image](https://user-images.githubusercontent.com/52276460/63835547-f4fca500-c977-11e9-8359-4d5a04b0fc2b.png)

**Comment by bardlokas** [comment]
Those are just warnings not errors. Can you try to make the 500 error appear while having the terminal open?

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63849990-77469280-c993-11e9-8b38-f04eba6e92b7.png)

all tables are from imomsw database.

**Comment by bardlokas** [comment]
And you are connected to the imomsw database?
http://localhost:5000/api/Portcall/1
This url now displays data?

**Comment by bardlokas** [comment]
"JwtIssuerOptions": {
        "Issuer": "placeholderIssuer",
        "Audience": "localhost"
    }
Add this to the bottom of your appsettings file.
so it looks like this:

`{
"ConnectionStrings": {
"OpenSSN": "User ID=postgres;Password=******;Host=localhost;Port=5432;Database=imomsw;",
"UserDatabase": ""
},
"AppSettings": {
"Secret" : "TopSekritSecretToken"
},
,
    "JwtIssuerOptions": {
        "Issuer": "placeholderIssuer",
        "Audience": "localhost"
    }
}`

**Comment by mgalil** [comment]
Unfortunately ..
get the same error

**Comment by bardlokas** [comment]
How is your appsettings file now? Copy the entire file please

**Comment by mgalil** [comment]
[appsettings.json.txt](https://github.com/Fundator/IMO-Maritime-Single-Window/files/3555203/appsettings.json.txt)

**Comment by bardlokas** [comment]
You are missing the JwtIssuerOptions i mentioned in my above comment.

**Comment by mgalil** [comment]
like this:

[appsettings.json.txt](https://github.com/Fundator/IMO-Maritime-Single-Window/files/3555246/appsettings.json.txt)

**Comment by mgalil** [comment]
![image](https://user-images.githubusercontent.com/52276460/63936945-8562e480-ca61-11e9-9285-a819ad29c1e8.png)

**Comment by bardlokas** [comment]
That error means that your password for the postgres user is wrong.
I see in your appsettings you have written "password=*****", remove this 
So it only says;
"OpenSSN": "User ID=user;Host=localhost;Port=5432;Database=imomsw;",

Unless you plan on using another user you set up yourself, then you have to write the password in that field.

**Comment by mgalil** [comment]
{
	"ConnectionStrings": {
		"OpenSSN": "User ID=user;Host=localhost;Port=5432;Database=imomsw;",
		"UserDatabase": ""
	},
	"AppSettings": {
		"Secret" : "TopSekritSecretToken"
	},
"	JwtIssuerOptions": { 
		"Issuer": "placeholderIssuer", "Audience": "localhost" }
}


![image](https://user-images.githubusercontent.com/52276460/63938570-66fee800-ca65-11e9-92e2-88bf9a83f7dd.png)

**Comment by bardlokas** [comment]
It says that your user has a password. So add the password you chose 
{
"ConnectionStrings": {
"OpenSSN": "User ID=user;Password=YOURPASSWORDHERE;Host=localhost;Port=5432;Database=imomsw;",
"UserDatabase": ""
},
"AppSettings": {
"Secret" : "TopSekritSecretToken"
},
" JwtIssuerOptions": {
"Issuer": "placeholderIssuer", "Audience": "localhost" }
}

**Comment by mgalil** [comment]
I applied the above appsettings.json you mentioned above, get the same error :

![image](https://user-images.githubusercontent.com/52276460/64075890-3a91d880-ccbe-11e9-9071-29d8ded0bd65.png)

**Comment by bardlokas** [comment]
It says that the password is wrong. Are you sure you wrote the correct password?
What did you write as a password when creating the user? And are you writing the same password in the appsettings?

**Comment by mgalil** [comment]
the password for user postgres is "Root1234" as written in appsettings.

**Comment by bardlokas** [comment]
But you aren't using the postgres user. You are referencing a user named "user".
Did you create a user in pgadmin named "postgres" with the password "Root1234" ?
If so, use that in the appsettings, not "user".

**Comment by mgalil** [comment]
- I entered this passowrd "Root1234" during postgresql installation 
- so I login to postgresql using postgres/Root1234
- I didn't create any user in pgadmin

**Comment by bardlokas** [comment]
It says you are using the user named "user" in your appsettings file. You have to use a user that exists.

**Comment by mgalil** [comment]
Error : Object Object

![image](https://user-images.githubusercontent.com/52276460/64162633-f890a000-ce3f-11e9-9c10-aaac2bd02936.png)
![image](https://user-images.githubusercontent.com/52276460/64162657-08a87f80-ce40-11e9-863b-1a150b87f322.png)

**Comment by bardlokas** [comment]
The part you posted from the terminal is not an error. You are looking for red text.

**Comment by mgalil** [comment]
no red text, just green "Info" lines.

**Comment by bardlokas** [comment]
Can you share your appsettings again?

**Comment by mgalil** [comment]
[appsettings.json.txt](https://github.com/Fundator/IMO-Maritime-Single-Window/files/3569144/appsettings.json.txt)

**Comment by bardlokas** [comment]
You have a space " JwtIssuerOptions" it should be "JwtIssuerOptions"

**Comment by bardlokas** [comment]
Did this fix your issues?

**Comment by mgalil** [comment]
thank you very much **Bardlokas** it's working with server and client .. but there is a bit problem with client access, all icons and images not appeared as below:

![image](https://user-images.githubusercontent.com/52276460/64248280-082be980-cf11-11e9-854b-069baaa1dbee.png)

![image](https://user-images.githubusercontent.com/52276460/64248368-301b4d00-cf11-11e9-9520-12aecd7b24bf.png)

**Comment by bardlokas** [comment]
Linking between client/server projects or something might not have been built correctly. If you open localhost:5000 it should display correctly.

**Comment by mgalil** [comment]
with localhost:5000 all images displayed correctly, but the problem only with localhost:4201

**Comment by bardlokas** [comment]
Rename the folder at this location:
IMO-Maritime-Single-Window\IMOMaritimeSingleWindow\Client\src\assets\images\Flags
to "flags".
As in: set it all to lower case.

**Comment by mgalil** [comment]
It's working .. thank you very bardlokas, Now and finally I can close this issue,
thank you.

**Comment by mgalil** [comment]
Hi bardlokas .. I can access client (localhost:4201) remotely but server (localhost:5000) only locally, is that only the difference between them.
