### ISSUE TITLE
server and client difference

### ISSUE THREAD

**Issue by mgalil** [Fundator/IMO-Maritime-Single-Window#99]
Hi bardlokas .. I can access client (localhost:4201) remotely but server (localhost:5000) only locally, is that only the difference between them, client for remote access and server for local access.

**Comment by bardlokas** [comment]
not sure i understand the question? What are you asking?

**Comment by mgalil** [comment]
what is the difference between client (localhost:4201) and server (localhost:5000), for me they are the same?

**Comment by bardlokas** [comment]
https://angular.io/guide/typescript-configuration

**Comment by bardlokas** [comment]
[Please confer with the wiki](https://github.com/Fundator/IMO-Maritime-Single-Window/wiki)

[Technical Document](https://github.com/Fundator/IMO-Maritime-Single-Window/files/2861904/WIKI.-.MSW.tech.doc.pdf)

**Comment by bardlokas** [comment]
If you require technical support please email me instead:
post@bardlokas.no

**Comment by mgalil** [comment]
sorry, you didn't understand me, I mean who will user sever interface and who is using client interface

**Comment by bardlokas** [comment]
It is described within the documents I provided

**Comment by bardlokas** [comment]
Short answer:
Client project is for the developer. The entire client project is transpiled down to minified .js filed located in the wwwroot directory of the server project when running the BuildFrontend.bat script.
The server project is what is deployed and used by a user.
